source 'https://rubygems.org'

gem 'rails', branch: '4.0-stable'
#gem 'turbolinks'
gem 'protected_attributes'
gem 'pg'
gem 'rails_admin'
gem 'rails_admin_nestable'
gem 'ckeditor'
gem 'devise'
gem 'cancan'
gem 'ancestry'
gem 'haml-rails'
gem 'carrierwave'
gem 'mini_magick'
gem 'gritter_notices'
gem 'kaminari'
gem 'yaml_db', github: 'lostapathy/yaml_db'
gem 'sass-rails'
gem 'bootstrap-sass', '~> 2.3.2.0'
gem 'compass-rails', github: "Compass/compass-rails", branch: "rails4-hack"
gem 'friendly_id', github: 'norman/friendly_id'
gem 'state_machine'
gem 'russian'
gem 'jquery-rails'
gem 'coffee-rails'

gem 'uglifier'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'letter_opener'
  gem 'thin'
end

gem 'unicorn'
gem 'capistrano'
gem 'debugger'
gem 'therubyracer'
gem 'execjs'
gem 'libv8'
