source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'pg'
gem 'rails_admin', github: 'niksan/rails_admin'
gem 'rails_admin_nestable'
gem 'ckeditor'
gem 'devise'
gem 'cancan'
gem 'ancestry'
gem 'haml-rails'
gem 'carrierwave'
gem 'mini_magick'
gem 'gritter', '1.0.3'
gem 'kaminari'
gem 'yaml_db'
gem 'sass-rails', '~> 4.0.0'
gem 'bootstrap-sass', '~> 2.3.2.0'
gem 'compass-rails', github: "Compass/compass-rails", branch: "rails4-hack"
gem 'friendly_id', github: 'norman/friendly_id'
gem 'state_machine'
gem 'russian'
gem 'jquery-rails'
gem 'coffee-rails', '~> 4.0.0'
gem 'roo'
gem 'paper_trail', github: 'airblade/paper_trail'
gem 'jbuilder', '~> 1.2'
gem 'turbolinks'

gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'letter_opener'
  gem 'thin'
  gem 'capistrano', '~> 3.0.0', require: false
#  gem 'capistrano-rails'
end

#gem 'capistrano-rvm', '~> 0.0.2'
gem 'unicorn'
gem 'debugger'
gem 'therubyracer'
gem 'execjs'
gem 'libv8'
