source 'https://rubygems.org'

gem 'rails', '3.2.14'
gem 'pg'
gem 'rails_admin'
gem 'rails_admin_nestable'
gem 'ckeditor'
gem 'devise'
gem 'cancan'
gem 'ancestry'
gem 'haml-rails'
gem 'carrierwave'
gem 'mini_magick'
gem 'gritter_notices'
gem 'kaminari'
gem 'yaml_db'
gem 'sass-rails',   '~> 3.2.3'
gem 'bootstrap-sass', '~> 2.3.2.0'
gem 'compass-rails'
gem 'friendly_id'
gem 'state_machine'
gem 'russian'
gem 'jquery-rails'
gem 'coffee-rails', '~> 3.2.1'
gem 'roo'

group :assets do
  gem 'uglifier', '>= 1.0.3'
  gem 'turbo-sprockets-rails3'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'letter_opener'
  gem 'thin'
end

gem 'unicorn'
gem 'capistrano'
gem 'debugger'
gem 'therubyracer'
gem 'execjs'
gem 'libv8'
