development:
  adapter: postgresql
  encoding: unicode
  database: webshop_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: webshop_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: webshop_development
  pool: 5
  username: postgres
  password:
